// One-time seed data for the pricing database, mirroring the site's
// current (corrected) price list. This only ever runs if the categories
// table is empty (see seedFromStaticDataIfEmpty in pricingStore.js) — it
// is not a source of truth once the database has rows, only a bootstrap.
export const STATIC_SEED_CATEGORIES = [
  {
    id: 'free-consultations',
    title: 'Free Consultations',
    desc: 'Complimentary first step appointments, and one specialist consultation.',
    items: [
      { name: 'Facial Analysis', price: 'Free' },
      { name: 'Face and Body Tightening Endolift Consultation', price: 'Free' },
      { name: 'Hair Loss Consultation', price: 'Free' },
      { name: 'Weight Management Consultation', price: 'Free' },
    ],
  },
  {
    id: 'diode-laser',
    title: '4 Wavelength Diode Laser',
    desc: 'Laser pricing by treatment area.',
    items: [
      { name: 'Half Face', price: '£30' },
      { name: 'Full Face and Neck', price: '£50' },
      { name: 'Full Neck', price: '£20' },
      { name: 'Forehead', price: '£20' },
      { name: 'Full Cheeks', price: '£15' },
      { name: 'Upper Lips', price: '£15' },
      { name: 'Chin', price: '£20' },
      { name: 'Chin & Lips', price: '£20' },
      { name: 'Side of Face', price: '£20' },
      { name: 'Back of Neck', price: '£20' },
      { name: 'Ears', price: '£15' },
      { name: 'Nose', price: '£15' },
      { name: 'Hand Fingers', price: '£20' },
      { name: 'Shoulder', price: '£25' },
      { name: 'Full Arms', price: '£55' },
      { name: 'Chest', price: '£40' },
      { name: 'Abdomen', price: '£50' },
      { name: 'Full Bikini', price: '£50' },
      { name: 'Lower Legs', price: '£40' },
      { name: 'Leg Tops', price: '£55' },
      { name: 'Full Legs', price: '£80' },
      { name: 'Toes', price: '£10' },
      { name: 'Full Back', price: '£90' },
      { name: 'Upper Back', price: '£40' },
      { name: 'Lower Back', price: '£40' },
      { name: 'Under Arms', price: '£25' },
    ],
  },
  {
    id: 'microneedling',
    title: 'Medical Grade Microneedling',
    desc: 'Face, hands, neck, or décolletage pricing.',
    items: [
      { name: 'Bronze: Microneedling', price: '£100' },
      { name: 'Silver: Microneedling + Chemical Peel', price: '£175' },
      { name: 'Gold: Microneedling + PRP', price: '£200' },
      { name: 'Diamond: Microneedling + Exosomes', price: '£200' },
    ],
  },
  {
    id: 'anti-wrinkle',
    title: 'Anti Wrinkle and Botox Treatments',
    desc: 'Targeted anti wrinkle pricing across facial and specialist areas.',
    items: [
      { name: 'Full Face', price: '£300' },
      { name: 'Upper Face (3 Areas)', price: '£180' },
      { name: 'Upper Face (3 Areas) + One Area', price: '£200' },
      { name: 'One Area', price: '£80' },
      { name: 'Nose Botox (Lifting, Slimming & Lines)', price: '£100' },
      { name: 'Lower Facelift Botox', price: '£150' },
      { name: 'Botox Neck Lift', price: '£225' },
      { name: 'Teeth Grinding / Face Slimming', price: '£200' },
      { name: 'Excessive Sweating Botox', price: '£350' },
      { name: 'Shoulder & Neck Pain Botox', price: '£350' },
      { name: 'Anti Wrinkle Treatment: One Area', price: '£80' },
    ],
  },
  {
    id: 'skin-boosters',
    title: 'Skin Boosters and Under Eye Treatments',
    desc: 'Session options taken from the provided price list.',
    items: [
      { name: 'Jalupro: 1 Session', price: '£150' },
      { name: 'Jalupro: 3 Sessions', price: '£350' },
      { name: 'Lumi Eyes: 1 Session', price: '£100' },
      { name: 'Lumi Eyes: 3 Sessions', price: '£250' },
      { name: 'Sunekos: 1 Session', price: '£175' },
      { name: 'Sunekos: 3 Sessions', price: '£475' },
      { name: 'Profhilo: 1 Session', price: '£175' },
      { name: 'Profhilo: 2 Sessions', price: '£300' },
    ],
  },
  {
    id: 'fillers',
    title: 'Fillers and Injectable Boosters',
    desc: 'Filler pricing across facial areas, plus skin refreshing treatments.',
    items: [
      { name: 'Lips Filler 1 ml', price: '£150' },
      { name: 'Jaw Filler', price: '£150' },
      { name: 'Cheeks Filler', price: '£150' },
      { name: 'Smile Line Filler', price: '£150' },
      { name: 'Sculptra', price: '£300' },
      { name: 'Radiesse', price: '£250' },
      { name: 'Chemical Peel', price: '£65' },
      { name: 'Vampire Facial Treatment', price: '£100' },
    ],
  },
  {
    id: 'body-treatments',
    title: 'Fat Dissolving and Body Treatments',
    desc: 'Body contouring and targeted body treatment pricing.',
    items: [
      { name: 'Fat Dissolving Injection', price: '£150' },
      { name: 'Microneedling (Cellulite/Stretch Marks)', price: '£150' },
      { name: 'Leg Spider Vein Removal', price: '£300' },
      { name: 'PRP for Cellulite Treatment', price: '£75' },
      { name: 'PRP for Stretch Marks & Scars', price: '£250' },
      { name: 'Fat Freeze or Lipolysis', price: '£150' },
      { name: 'RF for Tightening and Lifting', price: '£75' },
      { name: 'Other Body Areas', price: '£300 to £1,000' },
    ],
  },
  {
    id: 'wellness',
    title: 'Wellness, Hair Restoration, and Specialist Treatments',
    desc: 'Wellness injections, scalp work, and specialist treatment pricing.',
    items: [
      { name: 'Vitamin B12 Jab - Energy Booster', price: '£25' },
      { name: 'Vitamin C Jab - Immune Booster', price: '£25' },
      { name: 'Vitamin D Jab - Mood Booster', price: '£25' },
      { name: 'Biotin Injection for Hair Health', price: '£25' },
      { name: 'Bronze: 1 Meso', price: '£100' },
      { name: 'Silver: PRP + Meso', price: '£125' },
      { name: 'Gold: PRP + Microneedling + Exosomes', price: '£150' },
      { name: 'Diamond: PRP + Microneedling + Exosomes + Biotin Injection', price: '£200' },
      { name: 'Upper & Lower Eyelids (Periorbital Area)', price: '£250' },
      { name: 'Cheeks', price: '£200' },
      { name: 'Jawline', price: '£200' },
      { name: 'Neck', price: '£300' },
      { name: 'Full Face & Neck', price: '£500' },
      { name: 'Vaginal Tightening & Urinary Incontinence Treatment', price: '£300' },
      { name: 'Fungal Nail Infection Treatment (Onychomycosis)', price: '£200' },
    ],
  },
];
